### ISSUE TITLE
What does f2py_cmap mean?

### ISSUE THREAD

**Issue by ghost** [scivision/f2pyExamples#1]
https://github.com/scivision/f2py-examples/blob/14329a37fb9c38c8281d05b404d559295dd2a1c7/badprec.f90#L1-L14

It is not clear what do you mean by `unless matching .f2py_cmap`. What is `.f2py_cmap`?

Thank you

**Comment by scivision** [comment]
It was a typo it means to match the file 
. f2py_f2cmap as in the top level of this repo
